sudo: required
services:
  - docker

before_install:
  - docker build -t briceth/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run briceth/react-test npm test -- --coverage
# builder toutes les images
after_success:
  - docker build -t briceth/multi-client ./client
  - docker build -t briceth/multi-nginx ./nginx
  - docker build -t briceth/multi-server ./server
  - docker build -t briceth/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker
  - docker push briceth/multi-client
  - docker push briceth/multi-nginx
  - docker push briceth/multi-server
  - docker push briceth/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-034445389199
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
